baseurl = "/"
languageCode = "en-us"
theme = "hugo-theme-terminal"
paginate = 5

[params]
  contentTypeName = "post"
  themeColor = "pink"
  showMenuItems = 2
  fullWidthTheme = false
  centerTheme = true

[languages]
  [languages.en]
    title = "_MaVe_"
    subtitle = "bli bla blu"
    keywords = ""
    copyright = "Martin Verner"
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "_MaVe_"
      logoHomeLink = "/"

    [languages.en.menu]
    
      [[languages.en.menu.main]]
        identifier = "About"
        name = "About"
        url = "/about"
        
      [[languages.en.menu.main]]
        identifier = "GitHub"
        name = "GitHub"
        url = "/github"  
        
      [[languages.en.menu.main]]
        identifier = "Contact"
        name = "Contact"
        url = "/contact"
      
